### ISSUE TITLE
Could BeeOS fit on a floppy?

### ISSUE THREAD

**Issue by informer2016** [davxy/beeos#17]
Good day @davxy ! Please tell, could BeeOS fit inside a floppy? Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_ It seems that BeeOS size is less than 1.44MB, but I would like to make sure

**Comment by davxy** [comment]
Hi Informer. I don't think that there is any problem but I've never tried... so I've got no punctual responses to your question.
At the moment all I can say is:
- BeeOS kernel is surely less than 1.44 MB 
- Feel free to make all the tests you like and eventually modify the sources to achieve the result.
Davide

**Comment by informer2016** [comment]
@davxy Thank you very much for your reply. Please tell, do you have any interesting apps for BeeOS _(or is it only a kernel at this point?)_, and in what programming language they are written?

**Comment by davxy** [comment]
The project is supposed to be a didactical kernel so the apps are not the focus and (at this point) are mainly used to play with kernel features. Applications, as the kernel, are written in C
