### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by enty8080** [davxy/beeos#22]
![19D7FD46-79D2-4667-A6BC-7B7815177050](https://user-images.githubusercontent.com/54115104/83947566-7f840600-a820-11ea-9430-7c3ad0926f63.jpeg)

@davxy 
@Mcpg 
@informer2016 
@malbx 
@game-lover
linker could not found -lgcc flag.

**Comment by davxy** [comment]
BeeOS currently only supports 32 bit x86 targets (see the `-m32` flag in the gcc parameters) but looks like your host system only supports 64 bits targets, i.e. you don't have an x86 compatible toolchain.

Two options for you (I use Debian, hope that Kali has similar packages)

### Option 1

Install the gcc-multilib package.

```
$ sudo apt install gcc-multilib
$ make
```

### Option 2. 

Install an i686 toolchain and specify the compiler you want to use in the `CC` param

```
$ sudo apt install gcc-i686-linux-gnu
$ make CC=i686-linux-gnu-gcc
```

**Comment by enty8080** [comment]
@davxy Thanks! But I have one question. Does BeeOS has shell with Unix commands like ls, whoami, id and dd?

**Comment by davxy** [comment]
Unfortunately the system is not born to replace a complete Unix system but only as a learning tool so there is a limited amount of userland applications.

Current user space apps are here:
https://github.com/davxy/beeos/tree/master/user/src/bin

Anyway, nothing prevents you from building such applications and open a merge request :-)

Also note that the current shell is very primitive and do not support output redirection... implementing it is not a big issue
